package caio

object Exceptions {
  val testEx = new Exception("this is a test")
  val testEx2 = new Exception("this is a test 2")
}
